travis:
  secure:
    BINSTAR_TOKEN: lhVZdUSgfmq+aVkE+RonG3WvJ/fbCM3rSG2zhn7WhIk0uAUqf+LzDec8gqzWhFVrF8rBNAxI5wgZBfxhuIJt7dSZiTMRDecHAjjcItEsTeBrng2HgOtmv3ZT68MMZCsO+Km0rUcEWFvW+GwttfEyJIQ1PLxJOdkHCW2DCE4ntui4VEqhJbMFz9VztVYNKByV9BmTOh4kcazXKx7kCfVFny2U09s2OK86HqUusi2qabKRSZFtk7MEA162I+t/IYdfZSv9YCqOtGa1Lit5D1vns7ULBh7wlXmTTQDMMrZEgWM4/1ds/14g4isBQ5TCKCY6Ce5qP4V8Htgx+RyS4RFm26gHaoHJhatpcZv6yXc56nhAskXQVNMpf2Tv3m9ER7ssE17c6gjZHk1u2pcVBd8oYvOi4XhIOU9arF0LqX/shAVsVLnC2GIZvyjqBtjO/ufNrTA+G+xXP3oVVVT4LS2TvoiBvRRCPPQGqQBP/2soNCbC1uuceyMY2MIhdnsYC0ghG9ARnr7jeVgbLGo3SDMs5Z7sUxFSTWcYkv/85CgGTLQXVgmWxi2iAXFIedDMAXh80wOzcrvP9rElGWBHHGE9zonoVJu0GLAGVEYs8i5f6QDGdLeI/uaoaehprmqbiFxSmEbbtWKijmDoD5fUvqXKrowNL8plLxNmJJ7u2RVAWKw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
